Fix importing images and labels with filenames with multiple dots
SkalskiP/make-sense pull request #160
Opened 2021-05-04 17:53 UTC by h3ct0r

### Pre-flight checklist

- [X] Unit tests for all non-trivial changes
- [X] Tested locally
- [ ] Updated wiki no need

Labels and filenames with multiple dots now are working as intended.

2021-05-05 06:24 UTC, SkalskiP commented
Hi @h3ct0r :) Thank you for that PR. Looks good. Please remove comments and we can merge. ;)

2021-05-05 06:25 UTC, SkalskiP requested changes

2021-05-05 06:25 UTC, SkalskiP commented on src/utils/FileUtil.ts
> +        // fix for files with multiple dots
```suggestion
```

2021-05-05 06:25 UTC, SkalskiP commented on src/utils/FileUtil.ts
> +        // fix for files with multiple dots
```suggestion
```

2021-05-08 01:45 UTC, h3ct0r commented on src/utils/FileUtil.ts
> +        // fix for files with multiple dots
Comments were removed

2021-05-08 01:45 UTC, h3ct0r commented on src/utils/FileUtil.ts
> +        // fix for files with multiple dots
Comments were removed

2021-05-08 01:46 UTC, h3ct0r commented
> Hi @h3ct0r :) Thank you for that PR. Looks good. Please remove comments from your code and we can merge. ;)

Hi @SkalskiP, sure! the comments are now removed! If you need another change please let me know.

2021-05-08 07:51 UTC, SkalskiP commented
Thank you very much. @h3ct0r I know it may be to much to ask, but would it be possible to add some unit tests for those two functions?

2021-05-10 20:06 UTC, h3ct0r commented
> Thank you very much. @h3ct0r I know it may be to much to ask, but would it be possible to add some unit tests for those two functions?

Sure, unit test were added

2021-05-10 20:10 UTC, SkalskiP commented
Hi @h3ct0r! Thank you very much for your contribution. We are merging that PR into `develop`. Regards ;)

2021-05-10 20:10 UTC, merged